### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by liquid** [archSeer/ruby-mpd#34]
Hey Blaz @archSeer,

I’ve seen that you’ve incremented the version number in ruby-mpd but and released on Rubygems but in fact the code has not been tagged. Given that I’ve migrated the codebase onto Bundler, I thought I’d share with you what I do, it may be useful:

I use `rake release` after changing `version.rb`, this rake task comes from Bundler and it properly tags the codebase, pushes it up and then releases the gem onto Rubygems. So all release stuff can be done using a single command in the terminal.

Hopefully this will help.

— Attila

**Comment by archSeer** [comment]
I've went and manually tagged the versions that weren't tagged yet, didn't know it's a big deal.

Ah I see, I never used these tasks before, always did the procedure manually. Will look into using these in the future.
