### ISSUE TITLE
callback stops firing after a few hours

### ISSUE THREAD

**Issue by runsnbunsn** [archseer/ruby-mpd#40]
not sure if this is ruby-mpd related, but i didnt find a clue yet, maybe you can enlighten me

basically i have this code for handling the connection

```
def self.connect_mpd
    @mpd = MPD.new 'localhost', 6600, {callbacks: true} if @mpd == nil
    unless @mpd.connected?
      Rails.logger.info "Connecting to MPD . . ."
      @mpd.connect
      sleep 0.3
      @mpd.on :song do |song|
        Rails.logger.info "!!!!!!!!!!!!!! #{Time.now.to_s} MPD_SONG change: #{song.title} - #{song.artist} !!!"
      end
    end

  end
```

this block gets fired about every minute(or even more) and works fine basically

After a few hours(about 6-8) the callback just stops firing, but the connection to mpd is still there, application continuing to work normally. No clues about dropped connection in mpd.log

connection_timeout is set to 3600 in mpd.conf

using ruby-mpd 0.31, MPD 0.18, local only

any tips what could be wrong?

**Comment by specht** [comment]
I've got the same problem with the `:time` callback which fires once per second when a song is playing and it just stops after a while. This seems to be the same issue, as the connection is still working and commands still get passed to MPD, but the callback stops after a while.

**Comment by archSeer** [comment]
Hmm, sounds like the callback thread eventually times out and does not reconnect properly.

**Comment by mikerodrigues** [comment]
Which OS? Were you connecting to localhost? I've had two different MPD callback threads open to an MPD instance at localhost. They've both been up for two days without issue. I set `Thread.abort_on_exception = true` for both.
